name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  dev-deploy:
    name: Render Dev Deploy
    environment: DEV
    runs-on: ubuntu-latest
    
    steps: 
      - name: Deploy to dev
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
           api-key: ${{ secrets.RENDER_API_KEY_DEV }}


  prod-deploy:
    name: Render Prod Deploy
    environment: PROD
    needs: dev-deploy
    runs-on: ubuntu-latest
    
    steps: 
      - name: Deploy to prod
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID_PROD }}
           api-key: ${{ secrets.RENDER_API_KEY_PROD }}
